# Generated by Django 4.2.4 on 2023-08-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmostraFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amostra', models.CharField(blank=True, max_length=36, null=True)),
                ('id_foto', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25, null=True)),
                ('caminho', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
            ],
            options={
                'db_table': 'amostra_foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Amostras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amostra', models.CharField(max_length=36)),
                ('dt_amostra', models.DateTimeField(blank=True, null=True)),
                ('id_sensor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('dt_auditoria', models.DateTimeField(blank=True, null=True)),
                ('auditor', models.IntegerField(blank=True, null=True)),
                ('id_localizacao', models.CharField(blank=True, max_length=36, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('downloaded', models.BooleanField(blank=True, null=True)),
                ('deletado', models.BooleanField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('confianca', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('auditoria', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5, null=True)),
                ('seq', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('usuario_coleta', models.IntegerField(blank=True, null=True)),
                ('obs', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=4000, null=True)),
                ('classificacao_original', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('obs_admin', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5000, null=True)),
                ('endereco', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2000, null=True)),
                ('fit', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('chave_externa', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('precisao', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('dt_upload', models.DateTimeField(blank=True, null=True)),
                ('classificacao_matlab', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('classificacao_1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('classificacao_2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('classificador_1', models.IntegerField(blank=True, null=True)),
                ('classificador_2', models.IntegerField(blank=True, null=True)),
                ('vista', models.BooleanField(blank=True, null=True)),
                ('review', models.BooleanField(blank=True, null=True)),
                ('id_usuario_review', models.IntegerField(blank=True, null=True)),
                ('dt_review', models.DateTimeField(blank=True, null=True)),
                ('dt_vista', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_vista', models.IntegerField(blank=True, null=True)),
                ('classificador', models.IntegerField(blank=True, null=True)),
                ('dt_classificacao', models.DateTimeField(blank=True, null=True)),
                ('classificacao_temp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('classificacao_original_temp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('pressao', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('classificacao_cliente', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('dt_classificacao_cliente', models.DateTimeField(blank=True, null=True)),
                ('id_usuario_cliente_classificador', models.IntegerField(blank=True, null=True)),
                ('obs_app', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=150, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('classificacao_api', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('retorno_api', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('fit_api', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('confianca_api', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('vista_discordo', models.BooleanField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=36, null=True)),
                ('coletor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('inspecao', models.BooleanField(blank=True, null=True)),
                ('dt_inspecao', models.DateTimeField(blank=True, null=True)),
                ('ruido_api', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('espec', models.BooleanField(blank=True, null=True)),
                ('classificacao_br', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('predicao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=3, null=True)),
                ('decisao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=3, null=True)),
                ('id_inspecionar', models.IntegerField(blank=True, null=True)),
                ('id_inspecionar2', models.IntegerField(blank=True, null=True)),
                ('id_inspecionar3', models.IntegerField(blank=True, null=True)),
                ('url_image', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('pre_classificacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('v3', models.BooleanField(blank=True, null=True)),
                ('img', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amostras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlobStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
                ('dt_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'blob_storage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_classificacao', models.IntegerField()),
                ('id_amostra', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=64)),
                ('classificacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('id_usuario', models.IntegerField()),
                ('dt_classificacao', models.DateTimeField()),
                ('qualidade_audio', models.IntegerField()),
                ('certeza', models.IntegerField()),
            ],
            options={
                'db_table': 'classificacao_amostra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Classificacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_classificacao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
            ],
            options={
                'db_table': 'classificacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteFilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('id_filial', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente_filial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('razao_social', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300)),
                ('endereco', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('estado', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2, null=True)),
                ('cep', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CEP', max_length=8, null=True)),
                ('observacoes', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2000, null=True)),
                ('contato', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('id_timezone', models.IntegerField(blank=True, null=True)),
                ('matlab', models.BooleanField(blank=True, null=True)),
                ('id_cliente_master', models.IntegerField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('zoom', models.IntegerField(blank=True, null=True)),
                ('cnpj', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=18, null=True)),
                ('logo', models.TextField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiametroTubulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_diametro', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('ordem', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'diametro_tubulacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistanciaPercorrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('operador', models.IntegerField()),
                ('data_hora', models.DateTimeField()),
                ('distancia', models.FloatField()),
            ],
            options={
                'db_table': 'distancia_percorrida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_equipamento', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'equipamento_localizacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipamentosRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_relatorio', models.IntegerField()),
                ('id_equipamento', models.IntegerField()),
            ],
            options={
                'db_table': 'equipamentos_relatorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amostra', models.CharField(blank=True, max_length=36, null=True)),
                ('data', models.DateTimeField()),
                ('dados', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=4000, null=True)),
                ('tipo_acao', models.SmallIntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('origem', models.SmallIntegerField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAmostras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historico', models.CharField(max_length=36)),
                ('id_amostra', models.CharField(blank=True, max_length=36, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
            ],
            options={
                'db_table': 'historico_amostras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoAmostrasAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historico', models.CharField(max_length=36)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('dt_alteracao', models.DateTimeField(blank=True, null=True)),
                ('classificacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('id_amostra', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'historico_amostras_auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoDescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'historico_descricao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoSensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_historico', models.CharField(max_length=36)),
                ('id_sensor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('data_registro', models.DateTimeField()),
                ('amplificacao', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ganho', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tensao', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fuel', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'historico_sensores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localizacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_localizacao', models.CharField(max_length=36)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('endereco', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('complemento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('estado', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2, null=True)),
                ('contato', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('id_sensor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('cep', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CEP', max_length=10, null=True)),
            ],
            options={
                'db_table': 'localizacoes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LogAmostrasDupli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amostra', models.CharField(max_length=36)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('seq', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('seq_new', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('dt_ajuste', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'log_amostras_dupli',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ping', models.IntegerField()),
                ('dt_ping', models.DateTimeField(blank=True, null=True)),
                ('cod_status', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
            ],
            options={
                'db_table': 'ping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PosicaoVazamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_posicao', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'posicao_vazamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioAmostras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_relatorio', models.IntegerField()),
                ('id_amostra', models.CharField(max_length=36)),
                ('dt_delete', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relatorio_amostras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_foto', models.CharField(max_length=36)),
                ('id_relatorio', models.IntegerField(blank=True, null=True)),
                ('dt_registro', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('ext', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=4, null=True)),
            ],
            options={
                'db_table': 'relatorio_foto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelatorioVazamento',
            fields=[
                ('id_relatorio', models.AutoField(primary_key=True, serialize=False)),
                ('dt_relatorio', models.DateTimeField(blank=True, null=True)),
                ('dt_envio', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=36, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('id_status_relatorio', models.IntegerField(blank=True, null=True)),
                ('id_usuario_aprovacao', models.IntegerField(blank=True, null=True)),
                ('endereco', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=2000, null=True)),
                ('obs', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5000, null=True)),
                ('obs_aprovacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5000, null=True)),
                ('pressao', models.DecimalField(blank=True, decimal_places=6, max_digits=19, null=True)),
                ('nro_hidrometro', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('diametro', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('tipo_tubulacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('posicao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('tipo_vazamento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('dt_alteracao_status', models.DateTimeField(blank=True, null=True)),
                ('equipamentos', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5000, null=True)),
                ('tipo_pavimentacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('obs_tipo_vazamento', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5000, null=True)),
                ('nro_os', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('obs_inspecao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5000, null=True)),
                ('dt_delete', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
                ('longitude', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
                ('numero', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'relatorio_vazamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalvadoresAguaDiario',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('id_coletor', models.IntegerField()),
                ('data', models.DateField()),
                ('tipo_salvador', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('coletas_realizadas', models.IntegerField(blank=True, null=True)),
                ('fraudes_encontradas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salvadores_agua_diario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalvadoresAguaTotal',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('tipo_salvador', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15)),
                ('metros_cubicos_salvos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_coletas', models.IntegerField(blank=True, null=True)),
                ('total_fraudes', models.IntegerField(blank=True, null=True)),
                ('total_pontos_nao_confirmados', models.IntegerField(blank=True, null=True)),
                ('total_pontos_suspeitos_confirmados', models.IntegerField(blank=True, null=True)),
                ('total_vazamento_rede', models.IntegerField(blank=True, null=True)),
                ('total_vazamento_ramal', models.IntegerField(blank=True, null=True)),
                ('ultima_atualizacao', models.DateTimeField()),
                ('consecutividade_acuracia_mensal', models.IntegerField(blank=True, null=True)),
                ('consecutividade_coletas_inspecao_mensal', models.IntegerField(blank=True, null=True)),
                ('pontuacao_experiencia', models.IntegerField(blank=True, null=True)),
                ('pontuacao_conquista', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'salvadores_agua_total',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sensor', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=300, null=True)),
                ('dt_cadastro', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('dt_desativacao', models.DateTimeField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
                ('id_tipo', models.IntegerField(blank=True, null=True)),
                ('localizacao_atual', models.CharField(blank=True, max_length=36, null=True)),
                ('amplificacao', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ganho', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('tensao', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('fuel', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sensores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sequencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.IntegerField()),
                ('seq', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sequencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=30, null=True)),
            ],
            options={
                'db_table': 'status_ping',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusRelatorioVazamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_status_relatorio', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'status_relatorio_vazamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tagamostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_amostra', models.CharField(max_length=36)),
                ('tag', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5)),
            ],
            options={
                'db_table': 'tagAmostra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tag', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TempoAmostraClassificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tempo_amostra', models.IntegerField()),
                ('id_usuario', models.IntegerField()),
                ('id_amostra', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=40)),
                ('tempo_init', models.DateTimeField()),
                ('tempo_final', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tempo_amostra_classificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimerBr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_timer_br', models.IntegerField()),
                ('tempo_inicial', models.DateTimeField(blank=True, null=True)),
                ('tempo_final', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=9, max_digits=16, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'timer_br',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timezones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_timezone', models.IntegerField()),
                ('valor', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'timezones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('truck', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('water_tank', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'tipo_impacto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPavimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_pavimentacao', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'tipo_pavimentacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressao', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('ramal_metro_cubico', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rede_metro_cubico', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'tipo_pressao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRamalPressao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
            ],
            options={
                'db_table': 'tipo_ramal_pressao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposRota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipos_rota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipos_sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTubulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_tubulacao', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'tipo_tubulacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_usuario', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=3)),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoVazamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tipo_vazamento', models.IntegerField()),
                ('descricao', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
            ],
            options={
                'db_table': 'tipo_vazamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TokenPwd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=36)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('dt_token', models.DateTimeField(blank=True, null=True)),
                ('dt_validade', models.DateTimeField(blank=True, null=True)),
                ('usado', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'token_pwd',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_token', models.CharField(max_length=36)),
                ('dt_last_update', models.DateTimeField(blank=True, null=True)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tokens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField()),
                ('id_cliente', models.IntegerField()),
            ],
            options={
                'db_table': 'usuario_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200)),
                ('senha', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('nome', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=500, null=True)),
                ('telefone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('administrador', models.BooleanField(blank=True, null=True)),
                ('administrador_cliente', models.BooleanField(blank=True, null=True)),
                ('ativo', models.BooleanField(blank=True, null=True)),
                ('auditor', models.BooleanField(blank=True, null=True)),
                ('id_tipo_usuario', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=3, null=True)),
                ('gerar_senha', models.BooleanField(blank=True, null=True)),
                ('exibir_inspecao', models.BooleanField(blank=True, null=True)),
                ('id_mail_chimp', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('tour', models.BooleanField(blank=True, null=True)),
                ('master', models.BooleanField(blank=True, null=True)),
                ('operacao', models.BooleanField(blank=True, null=True)),
                ('funcao_dupla', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
